package edu.pitt.cs;

import static org.hamcrest.MatcherAssert.assertThat;
import org.junit.FixMethodOrder;
import org.junit.runners.MethodSorters;
import java.time.Duration;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import org.openqa.selenium.chrome.ChromeOptions;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class D3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--headless");
    driver = new ChromeDriver(options);

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void tEST1LINKS() {
    // Test name: TEST-1-LINKS
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/ |
    driver.get("http://localhost:8080/");
    // 2 | storeAttribute | linkText=Reset@href | reset
    {
      WebElement element = driver.findElement(By.linkText("Reset"));
      String attribute = element.getAttribute("href");
      vars.put("reset", attribute);
    }
    // 3 | assert | reset | /reset
    assertEquals(vars.get("reset").toString(), "http://localhost:8080/reset");
  }

  @Test
  public void tEST2RESET() {
    // Test name: TEST-2-RESET
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/ |
    driver.get("http://localhost:8080/");
    // 2 | runScript | document.cookie = "1=true";document.cookie =
    // "2=true";document.cookie = "3=true"; |
    js.executeScript("document.cookie = \"1=true\";document.cookie = \"2=true\";document.cookie = \"3=true\";");
    // 3 | click | linkText=Reset |
    driver.findElement(By.linkText("Reset")).click();
    // 4 | assertText | xpath=/html/body/div/main/div[1]/div/ul/li[1] | ID 1.
    // Jennyanydots
    assertThat(driver.findElement(By.xpath("/html/body/div/main/div[1]/div/ul/li[1]")).getText(),
        is("ID 1. Jennyanydots"));
    // 5 | assertText | xpath=/html/body/div/main/div[1]/div/ul/li[2] | ID 2. Old
    // Deuteronomy
    assertThat(driver.findElement(By.xpath("/html/body/div/main/div[1]/div/ul/li[2]")).getText(),
        is("ID 2. Old Deuteronomy"));
    // 6 | assertText | xpath=/html/body/div/main/div[1]/div/ul/li[3] | ID 3.
    // Mistoffelees
    assertThat(driver.findElement(By.xpath("/html/body/div/main/div[1]/div/ul/li[3]")).getText(),
        is("ID 3. Mistoffelees"));
  }

  @Test
  public void tEST3CATALOG() {
    // Test name: TEST-3-CATALOG
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/ |
    driver.get("http://localhost:8080/");
    // 2 | click | linkText=Catalog |
    driver.findElement(By.linkText("Catalog")).click();
    // 3 | storeAttribute | xpath=/html/body/div/main/div[1]/ol/li[2]/img@src | cat2
    {
      WebElement element = driver.findElement(By.xpath("/html/body/div/main/div[1]/ol/li[2]/img"));
      String attribute = element.getAttribute("src");
      vars.put("cat2", attribute);
    }
    // 4 | assert | cat2 | /images/cat2.jpg
    assertEquals(vars.get("cat2").toString(), "http://localhost:8080/images/cat2.jpg");
  }

  @Test
  public void tEST5RENTACAT() {
    // Test name: TEST-5-RENT-A-CAT
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/ |
    driver.get("http://localhost:8080/");
    // 2 | click | linkText=Rent-A-Cat |
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    // 3 | assertElementPresent | xpath=//button[contains(.,'Rent')] |
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[contains(.,\'Rent\')]"));
      assert (elements.size() > 0);
    }
    // 4 | assertElementPresent | xpath=//button[contains(.,'Return')] |
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[contains(.,\'Return\')]"));
      assert (elements.size() > 0);
    }
  }

  @Test
  public void tEST4LISTING() {
    // Test name: TEST-4-LISTING
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/ |
    driver.get("http://localhost:8080/");
    // 2 | click | linkText=Catalog |
    driver.findElement(By.linkText("Catalog")).click();
    // 3 | storeXpathCount | xpath=/html/body/div/main/div[1]/div/ul/li | count
    vars.put("count", driver.findElements(By.xpath("/html/body/div/main/div[1]/div/ul/li")).size());
    // 4 | assert | count | 3
    assertEquals(vars.get("count").toString(), "3");
    // 5 | assertText | xpath=/html/body/div/main/div[1]/div/ul/li[3] | ID 3.
    // Mistoffelees
    assertThat(driver.findElement(By.xpath("/html/body/div/main/div[1]/div/ul/li[3]")).getText(),
        is("ID 3. Mistoffelees"));
  }

  @Test
  public void tEST6RENT() {
    // Test name: TEST-6-RENT
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/ |
    driver.get("http://localhost:8080/");
    // 2 | runScript | document.cookie = "1=false";document.cookie =
    // "2=false";document.cookie = "3=false"; |
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    // 3 | click | linkText=Rent-A-Cat |
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    // 4 | click | id=rentID |
    driver.findElement(By.id("rentID")).click();
    // 5 | type | id=rentID | 1
    driver.findElement(By.id("rentID")).sendKeys("1");
    // 6 | click | css=.form-group:nth-child(3) .btn |
    driver.findElement(By.cssSelector(".form-group:nth-child(3) .btn")).click();
    // 7 | assertText | xpath=/html/body/div/main/div[1]/div/ul/li[1] | Rented out
    assertThat(driver.findElement(By.xpath("/html/body/div/main/div[1]/div/ul/li[1]")).getText(), is("Rented out"));
    // 8 | assertText | xpath=/html/body/div/main/div[1]/div/ul/li[2] | ID 2. Old
    // Deuteronomy
    assertThat(driver.findElement(By.xpath("/html/body/div/main/div[1]/div/ul/li[2]")).getText(),
        is("ID 2. Old Deuteronomy"));
    // 9 | assertText | xpath=/html/body/div/main/div[1]/div/ul/li[3] | ID 3.
    // Mistoffelees
    assertThat(driver.findElement(By.xpath("/html/body/div/main/div[1]/div/ul/li[3]")).getText(),
        is("ID 3. Mistoffelees"));
    // 10 | assertText | id=rentResult | Success!
    assertThat(driver.findElement(By.id("rentResult")).getText(), is("Success!"));
  }

  @Test
  public void tEST7RETURN() {
    // Test name: TEST-7-RETURN
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/ |
    driver.get("http://localhost:8080/");
    // 2 | runScript | document.cookie = "1=false";document.cookie =
    // "2=true";document.cookie = "3=false"; |
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=true\";document.cookie = \"3=false\";");
    // 3 | click | linkText=Rent-A-Cat |
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    // 4 | click | id=returnID |
    driver.findElement(By.id("returnID")).click();
    // 5 | type | id=returnID | 2
    driver.findElement(By.id("returnID")).sendKeys("2");
    // 6 | click | css=.form-group:nth-child(4) .btn |
    driver.findElement(By.cssSelector(".form-group:nth-child(4) .btn")).click();
    // 7 | assertText | xpath=/html/body/div/main/div[1]/div/ul/li[1] | ID 1.
    // Jennyanydots
    assertThat(driver.findElement(By.xpath("/html/body/div/main/div[1]/div/ul/li[1]")).getText(),
        is("ID 1. Jennyanydots"));
    // 8 | assertText | xpath=/html/body/div/main/div[1]/div/ul/li[2] | ID 2. Old
    // Deuteronomy
    assertThat(driver.findElement(By.xpath("/html/body/div/main/div[1]/div/ul/li[2]")).getText(),
        is("ID 2. Old Deuteronomy"));
    // 9 | assertText | xpath=/html/body/div/main/div[1]/div/ul/li[3] | ID 3.
    // Mistoffelees
    assertThat(driver.findElement(By.xpath("/html/body/div/main/div[1]/div/ul/li[3]")).getText(),
        is("ID 3. Mistoffelees"));
    // 10 | assertText | id=returnResult | Success!
    assertThat(driver.findElement(By.id("returnResult")).getText(), is("Success!"));
  }

  @Test
  public void tEST8FEEDACAT() {
    // Test name: TEST-8-FEED-A-CAT
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/ |
    driver.get("http://localhost:8080/");
    // 2 | click | linkText=Feed-A-Cat |
    driver.findElement(By.linkText("Feed-A-Cat")).click();
    // 3 | assertElementPresent | xpath=//button[contains(.,'Feed')] |
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[contains(.,\'Feed\')]"));
      assert (elements.size() > 0);
    }
  }

  @Test
  public void tEST9FEED() {
    // Test name: TEST-9-FEED
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/ |
    driver.get("http://localhost:8080/");
    // 2 | click | linkText=Feed-A-Cat |
    driver.findElement(By.linkText("Feed-A-Cat")).click();
    // 3 | click | id=catnips |
    driver.findElement(By.id("catnips")).click();
    // 4 | type | id=catnips | 6
    driver.findElement(By.id("catnips")).sendKeys("6");
    // 5 | click | css=.btn |
    driver.findElement(By.cssSelector(".btn")).click();
    // 6 | waitForElementVisible | xpath=//*[@id='feedResult' and text()='Nom, nom,
    // nom.'] | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions
          .visibilityOfElementLocated(By.xpath("//*[@id=\'feedResult\' and text()=\'Nom, nom, nom.\']")));
    }
    // 7 | assertText | id=feedResult | Nom, nom, nom.
    assertThat(driver.findElement(By.id("feedResult")).getText(), is("Nom, nom, nom."));
  }

  // @Test
  // public void tEST10GREETACAT() {
  // // Test name: TEST-10-GREET-A-CAT
  // // Step # | name | target | value
  // // 1 | open | http://localhost:8080/ |
  // driver.get("http://localhost:8080/");
  // // 2 | click | linkText=Greet-A-Cat |
  // driver.findElement(By.linkText("Greet-A-Cat")).click();
  // // 3 | assertElementPresent | xpath=//h4[contains(.,'Meow!Meow!Meow!')] |
  // {
  // List<WebElement> elements =
  // driver.findElements(By.linkText("Meow!Meow!Meow!"));
  // assert (elements.size() > 0);
  // }
  // }

  // @Test
  // public void tEST11GREETACATWITHNAME() {
  // // Test name: TEST-11-GREET-A-CAT-WITH-NAME
  // // Step # | name | target | value
  // // 1 | open | http://localhost:8080/greet-a-cat/Jennyanydots |
  // driver.get("http://localhost:8080/greet-a-cat/Jennyanydots");
  // // 2 | assertElementPresent | xpath=//h4[contains(.,'Meow! from
  // Jennyanydots.')]
  // // |
  // {
  // List<WebElement> elements = driver.findElements(By.linkText("Meow! from
  // Jennyanydots."));
  // assert (elements.size() > 0);
  // }
  // }
}
